#file: noinspection SpellCheckingInspection
with-expecter: true
dir: "{{.InterfaceDir}}"
inpackage: true
packages:
  github.com/metamogul/timing:
    interfaces:
      Action:
  github.com/metamogul/timing/simulated_time:
    interfaces:
      eventGenerator: