#file: noinspection SpellCheckingInspection
packages:
  github.com/metamogul/timing:
    config:
      with-expecter: true
      dir: "{{.InterfaceDir}}"
      inpackage: true
      recursive: true
    interfaces:
      Action:
      eventGenerator: